### PR TITLE
Fix NIO authentication on GCE VMs

### PR DESCRIPTION
**Pull request by medb**
Tested with:
```
gcloud dataproc clusters create broad-01 --image-version=1.3
./gradlew --rerun-tasks sparkJar
gcloud dataproc jobs submit spark --cluster broad-01 --class repro_package.Main --jars build/libs/nio-auth-repro-package-1.0-spark.jar --properties=spark.driver.extraClassPath=nio-auth-repro-package-1.0-spark.jar,spark.executor.extraClassPath=nio-auth-repro-package-1.0-spark.jar -- <BUCKET> /<FILE> --sparkMaster yarn
```

### CODE REVIEW

**Comment by jean-philippe-martin** [comment]
Interesting, thank you! I'll have to run it when I get the chance. I think there was a reason we had to use shading, though, I'll have to think about it.

**Comment by medb** [comment]
I suspect that there is regression in shading of newer versions of `google-cloud-nio` library, maybe they can fix it, so you will be able to use shaded dependency.

**Comment by jean-philippe-martin** [comment]
Yes! Trying this with the "preview" cluster, I can confirm I get "CloudStorageFileSystem.forBucket: works". That's great! Same with the "1.3" cluster.

It fails with the "default" 1.2 cluster, with "java.lang.NoSuchMethodError". But using the newer cluster software should be fine.

One concern is that this breaks the local execution somehow. It fails with "Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/JsonFactory".

**Comment by medb** [comment]
I guess you can relocate `com/fasterxml` instead of excluding it from shaded jar as I did, to fix local execution.

**Comment by jean-philippe-martin** [comment]
Indeed, that works!

**Comment by lbergelson** [comment]
So there's no easy way for us to switch to the unshaded version, because we have hard dependencies on guava 18 and a bizarro protobuff version.  Is it possible to fix the shaded library?  I'm not sure I understand from this what the issue is.

**Comment by medb** [comment]
@lbergelson Yes, it should be possible to fix nio-auth library shading, but you need to ask about it google-cloud-java team [here](https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2453).

Note that issue with shaded library not related to Dataproc, because it manifests itself on plain GCE VM without any modifications.

**Comment by jean-philippe-martin** [comment]
@medb if you can tell me *what* is wrong with the shading, I can submit a fix for review.

**Comment by medb** [comment]
Unfortunately I can not, because I didn't dig into it. I just tested this repro app with and without shading on non-Dataproc GCE VM and with shading it fails - this is everything what I know.

**Comment by lbergelson** [comment]
And the changes to the fasterxml were important in some way?  Or just switching to the non-shaded?

**Comment by lbergelson** [comment]
Interestingly, there's a number of files in `METAINF/services` which don't seem to have been properly updated by the shading. 

`com.fasterxml.jackson.core.JsonFactory`

**Comment by medb** [comment]
IIRC without shading/excluding `fasterxml` repro app fails, because conflicting version of this library already available in Hadoop/Spark class path on Dataproc VMs.

**Comment by lbergelson** [comment]
There's definitely a bug in the shading of the `META-INF/service/` files that point to plugin classes, they aren't updated to point to the shaded versions.  However... fixing that doesn't fix the issue when running with the shaded version...

**Comment by lbergelson** [comment]
I opened a bug about the shading issue here: https://github.com/GoogleCloudPlatform/google-cloud-java/issues/3540

**Pull request closed without merging**
